Attribute VB_Name = "Compare_and_Update"
Option Compare Database
Option Explicit

Global TVMINE As DAO.Database
Global TVOTH As DAO.Database
Global TVMINEGM As DAO.Database
Global TVOTHGM As DAO.Database
Global MYGMTABLE As Recordset
Global OTHGMTABLE As Recordset
Global MYVALIDGOODSTABLE As Recordset
Global OTHVALIDGOODSTABLE As Recordset



Public Function Compare_Valid_Goods()
'Compare my Valid_goods table with other GM's table.
'OTHER GM'S FILE WILL BE IN C:\WINDOWS\OFFICE\ACCESS\TRIBES\COPY

Set TVWKSPACE = DBEngine.Workspaces(0)

Set TVMINE = TVWKSPACE.OpenDatabase("c:\windows\office\access\tribes\TV.accdb", False, False)
Set TVOTH = TVWKSPACE.OpenDatabase("c:\windows\office\access\tribes\COPY\TV.accdb", False, False)

Set MYGMTABLE = TVMINE.OpenRecordset("GM")
MYGMTABLE.index = "PRIMARYKEY"
MYGMTABLE.MoveFirst

Set OTHGMTABLE = TVOTH.OpenRecordset("GM")
OTHGMTABLE.index = "PRIMARYKEY"
OTHGMTABLE.MoveFirst

FILEGM = "c:\windows\office\access\tribes\" & MYGMTABLE![FILE]
Set TVMINEGM = TVWKSPACE.OpenDatabase(FILEGM, False, False)
   
FILEGM = "c:\windows\office\access\tribes\COPY\" & OTHGMTABLE![FILE]
Set TVOTHGM = TVWKSPACE.OpenDatabase(FILEGM, False, False)
   
Forms![OTHER FUNCTIONS]![Status] = "VALID GOODS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALIDGOODSTABLE = TVMINEGM.OpenRecordset("VALID_GOODS")
MYVALIDGOODSTABLE.index = "primarykey"
MYVALIDGOODSTABLE.MoveFirst
  

Set OTHVALIDGOODSTABLE = TVOTHGM.OpenRecordset("VALID_GOODS")
OTHVALIDGOODSTABLE.index = "primarykey"
OTHVALIDGOODSTABLE.MoveFirst
  
Do Until OTHVALIDGOODSTABLE.EOF

   MYVALIDGOODSTABLE.MoveFirst
   MYVALIDGOODSTABLE.Seek "=", OTHVALIDGOODSTABLE![GOODS]
   If MYVALIDGOODSTABLE.NoMatch Then
      MYVALIDGOODSTABLE.AddNew
      MYVALIDGOODSTABLE![GOODS] = OTHVALIDGOODSTABLE![GOODS]
      MYVALIDGOODSTABLE![TABLE] = OTHVALIDGOODSTABLE![TABLE]
      MYVALIDGOODSTABLE![SHORTNAME] = OTHVALIDGOODSTABLE![SHORTNAME]
      MYVALIDGOODSTABLE![RATING] = OTHVALIDGOODSTABLE![RATING]
      MYVALIDGOODSTABLE![BASE SELL PRICE] = OTHVALIDGOODSTABLE![BASE SELL PRICE]
      MYVALIDGOODSTABLE![BASE BUY PRICE] = OTHVALIDGOODSTABLE![BASE BUY PRICE]
      MYVALIDGOODSTABLE![SPRING] = OTHVALIDGOODSTABLE![SPRING]
      MYVALIDGOODSTABLE![SUMMER] = OTHVALIDGOODSTABLE![SUMMER]
      MYVALIDGOODSTABLE![AUTUMN] = OTHVALIDGOODSTABLE![AUTUMN]
      MYVALIDGOODSTABLE![WINTER] = OTHVALIDGOODSTABLE![WINTER]
      MYVALIDGOODSTABLE![WEIGHT] = OTHVALIDGOODSTABLE![WEIGHT]
      MYVALIDGOODSTABLE![CARRIES] = OTHVALIDGOODSTABLE![CARRIES]
      MYVALIDGOODSTABLE.UPDATE
   End If

   OTHVALIDGOODSTABLE.MoveNext
   If OTHVALIDGOODSTABLE.EOF Then
      Exit Do
   End If

Loop
MYVALIDGOODSTABLE.Close
OTHVALIDGOODSTABLE.Close
Forms![OTHER FUNCTIONS]![Status] = "VALID GOODS Table ENDS"
Forms![OTHER FUNCTIONS].Repaint

End Function

Public Function Compare_my_TV_with_other_TV()
Dim MYACTIVITIESTABLE As Recordset
Dim OTHACTIVITIESTABLE As Recordset
Dim MYACTIVITYTABLE As Recordset
Dim OTHACTIVITYTABLE As Recordset
Dim MYENCOUNTERSTABLE As Recordset
Dim OTHENCOUNTERSTABLE As Recordset
Dim MYIMPLEMENTSTABLE As Recordset
Dim OTHIMPLEMENTSTABLE As Recordset
Dim MYRESEARCHTABLE As Recordset
Dim OTHRESEARCHTABLE As Recordset
Dim MYVALID_BUILDINGSTABLE As Recordset
Dim OTHVALID_BUILDINGSTABLE As Recordset
Dim MYVALID_CLIMATETABLE As Recordset
Dim OTHVALID_CLIMATETABLE As Recordset
Dim MYVALID_CROPSTABLE As Recordset
Dim OTHVALID_CROPSTABLE As Recordset
Dim MYVALID_MINERALSTABLE As Recordset
Dim OTHVALID_MINERALSTABLE As Recordset
Dim MYVALID_SKILLSTABLE As Recordset
Dim OTHVALID_SKILLSTABLE As Recordset
Dim MYVALID_SHIPSTABLE As Recordset
Dim OTHVALID_SHIPSTABLE As Recordset
Dim ACT_ACTIVITY As String
Dim ACT_ITEM As String
Dim ACT_TYPE As String
Dim ACT_GOOD As String

'Compare my TV.accdb against other GM's TV.accdb
'OTHER GM'S FILE WILL BE IN C:\WINDOWS\OFFICE\ACCESS\TRIBES\COPY
' The tables compared are - ACTIVITIES, ACTIVITY, ENCOUNTERS, IMPLEMENTS, RESEARCH, VALID_BUILDINGS, VALID_CLIMATE, VALID_CROPS
' VALID_MINERALS, VALID_SKILLS, VALID_SHIPS

Set TVWKSPACE = DBEngine.Workspaces(0)

Set TVMINE = TVWKSPACE.OpenDatabase("c:\windows\office\access\tribes\TV.accdb", False, False)
Set TVOTH = TVWKSPACE.OpenDatabase("c:\windows\office\access\tribes\COPY\TV.accdb", False, False)

'ACTIVITIES
Forms![OTHER FUNCTIONS]![Status] = "ACTIVITIES Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYACTIVITIESTABLE = TVMINE.OpenRecordset("ACTIVITIES")
MYACTIVITIESTABLE.index = "primarykey"
MYACTIVITIESTABLE.MoveFirst

Set OTHACTIVITIESTABLE = TVOTH.OpenRecordset("ACTIVITIES")
OTHACTIVITIESTABLE.index = "primarykey"
OTHACTIVITIESTABLE.MoveFirst
  
Do Until OTHACTIVITIESTABLE.EOF

   MYACTIVITIESTABLE.MoveFirst
   MYACTIVITIESTABLE.Seek "=", OTHACTIVITIESTABLE![ACTIVITY], OTHACTIVITIESTABLE![ITEM], OTHACTIVITIESTABLE![TYPE]
   If MYACTIVITIESTABLE.NoMatch Then
      MYACTIVITIESTABLE.AddNew
      MYACTIVITIESTABLE![ACTIVITY] = OTHACTIVITIESTABLE![ACTIVITY]
      MYACTIVITIESTABLE![ITEM] = OTHACTIVITIESTABLE![ITEM]
      MYACTIVITIESTABLE![TYPE] = OTHACTIVITIESTABLE![TYPE]
      MYACTIVITIESTABLE![SHORTNAME] = OTHACTIVITIESTABLE![SHORTNAME]
      MYACTIVITIESTABLE![SKILL LEVEL] = OTHACTIVITIESTABLE![SKILL LEVEL]
      MYACTIVITIESTABLE![research] = OTHACTIVITIESTABLE![research]
      MYACTIVITIESTABLE![NUMBER OF ITEMS] = OTHACTIVITIESTABLE![NUMBER OF ITEMS]
      MYACTIVITIESTABLE![PEOPLE] = OTHACTIVITIESTABLE![PEOPLE]
      MYACTIVITIESTABLE![GOODS_USED] = OTHACTIVITIESTABLE![GOODS_USED]
      MYACTIVITIESTABLE![GOOD_PRODUCED] = OTHACTIVITIESTABLE![GOOD_PRODUCED]
      MYACTIVITIESTABLE![SECOND SKILL] = OTHACTIVITIESTABLE![SECOND SKILL]
      MYACTIVITIESTABLE![SECOND SKILL LEVEL] = OTHACTIVITIESTABLE![SECOND SKILL LEVEL]
      MYACTIVITIESTABLE![THIRD SKILL] = OTHACTIVITIESTABLE![THIRD SKILL]
      MYACTIVITIESTABLE![THIRD SKILL LEVEL] = OTHACTIVITIESTABLE![THIRD SKILL LEVEL]
      MYACTIVITIESTABLE![FORTH SKILL] = OTHACTIVITIESTABLE![FORTH SKILL]
      MYACTIVITIESTABLE![FORTH SKILL LEVEL] = OTHACTIVITIESTABLE![FORTH SKILL LEVEL]
      MYACTIVITIESTABLE.UPDATE
   End If

   OTHACTIVITIESTABLE.MoveNext
   If OTHACTIVITIESTABLE.EOF Then
      Exit Do
   End If

Loop
MYACTIVITIESTABLE.Close
OTHACTIVITIESTABLE.Close

'ACTIVITY
Forms![OTHER FUNCTIONS]![Status] = "ACTIVITY Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYACTIVITYTABLE = TVMINE.OpenRecordset("ACTIVITY")
MYACTIVITYTABLE.index = "primarykey"
MYACTIVITYTABLE.MoveFirst

Set OTHACTIVITYTABLE = TVOTH.OpenRecordset("ACTIVITY")
OTHACTIVITYTABLE.index = "primarykey"
OTHACTIVITYTABLE.MoveFirst
  
ACT_ACTIVITY = OTHACTIVITYTABLE![ACTIVITY]
ACT_ITEM = OTHACTIVITYTABLE![ITEM]
ACT_TYPE = OTHACTIVITYTABLE![TYPE]
ACT_GOOD = OTHACTIVITYTABLE![GOOD]

Do Until OTHACTIVITYTABLE.EOF

   MYACTIVITYTABLE.MoveFirst
   MYACTIVITYTABLE.Seek "=", ACT_ACTIVITY, ACT_ITEM, ACT_TYPE, ACT_GOOD
   If MYACTIVITYTABLE.NoMatch Then
      MYACTIVITYTABLE.AddNew
      MYACTIVITYTABLE![ACTIVITY] = OTHACTIVITYTABLE![ACTIVITY]
      MYACTIVITYTABLE![ITEM] = OTHACTIVITYTABLE![ITEM]
      MYACTIVITYTABLE![TYPE] = OTHACTIVITYTABLE![TYPE]
      MYACTIVITYTABLE![GOOD] = OTHACTIVITYTABLE![GOOD]
      MYACTIVITYTABLE![NUMBER] = OTHACTIVITYTABLE![NUMBER]
      MYACTIVITYTABLE.UPDATE
   End If

   OTHACTIVITYTABLE.MoveNext
   If OTHACTIVITYTABLE.EOF Then
      Exit Do
   End If
   ACT_ACTIVITY = OTHACTIVITYTABLE![ACTIVITY]
   ACT_ITEM = OTHACTIVITYTABLE![ITEM]
   ACT_TYPE = OTHACTIVITYTABLE![TYPE]
   ACT_GOOD = OTHACTIVITYTABLE![GOOD]

Loop
MYACTIVITYTABLE.Close
OTHACTIVITYTABLE.Close

'ENCOUNTERS
Forms![OTHER FUNCTIONS]![Status] = "ENCOUNTERS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYENCOUNTERSTABLE = TVMINE.OpenRecordset("ENCOUNTERS")
MYENCOUNTERSTABLE.index = "primarykey"
MYENCOUNTERSTABLE.MoveFirst

Set OTHENCOUNTERSTABLE = TVOTH.OpenRecordset("ENCOUNTERS")
OTHENCOUNTERSTABLE.index = "primarykey"
OTHENCOUNTERSTABLE.MoveFirst
  
Do Until OTHENCOUNTERSTABLE.EOF

   MYENCOUNTERSTABLE.MoveFirst
   MYENCOUNTERSTABLE.Seek "=", OTHENCOUNTERSTABLE![ENCOUNTER NUMBER], OTHENCOUNTERSTABLE![SEQ NUM]
   If MYENCOUNTERSTABLE.NoMatch Then
      MYENCOUNTERSTABLE.AddNew
      MYENCOUNTERSTABLE![ENCOUNTER NUMBER] = OTHENCOUNTERSTABLE![ENCOUNTER NUMBER]
      MYENCOUNTERSTABLE![SEQ NUM] = OTHENCOUNTERSTABLE![SEQ NUM]
      MYENCOUNTERSTABLE![ENCOUNTER] = OTHENCOUNTERSTABLE![ENCOUNTER]
      MYENCOUNTERSTABLE![TYPE] = OTHENCOUNTERSTABLE![TYPE]
      MYENCOUNTERSTABLE.UPDATE
   End If

   OTHENCOUNTERSTABLE.MoveNext
   If OTHENCOUNTERSTABLE.EOF Then
      Exit Do
   End If
Loop
MYENCOUNTERSTABLE.Close
OTHENCOUNTERSTABLE.Close

'IMPLEMENTS
Forms![OTHER FUNCTIONS]![Status] = "IMPLEMENTS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYIMPLEMENTSTABLE = TVMINE.OpenRecordset("IMPLEMENTS")
MYIMPLEMENTSTABLE.index = "primarykey"
MYIMPLEMENTSTABLE.MoveFirst

Set OTHIMPLEMENTSTABLE = TVOTH.OpenRecordset("IMPLEMENTS")
OTHIMPLEMENTSTABLE.index = "primarykey"
OTHIMPLEMENTSTABLE.MoveFirst
  
Do Until OTHIMPLEMENTSTABLE.EOF

   MYIMPLEMENTSTABLE.MoveFirst
   MYIMPLEMENTSTABLE.Seek "=", OTHIMPLEMENTSTABLE![ACTIVITY], OTHIMPLEMENTSTABLE![ITEM], OTHIMPLEMENTSTABLE![IMPLEMENT]
   If MYIMPLEMENTSTABLE.NoMatch Then
      MYIMPLEMENTSTABLE.AddNew
      MYIMPLEMENTSTABLE![ACTIVITY] = OTHIMPLEMENTSTABLE![ACTIVITY]
      MYIMPLEMENTSTABLE![ITEM] = OTHIMPLEMENTSTABLE![ITEM]
      MYIMPLEMENTSTABLE![IMPLEMENT] = OTHIMPLEMENTSTABLE![IMPLEMENT]
      MYIMPLEMENTSTABLE![Modifier] = OTHIMPLEMENTSTABLE![Modifier]
      MYIMPLEMENTSTABLE.UPDATE
   End If

   OTHIMPLEMENTSTABLE.MoveNext
   If OTHIMPLEMENTSTABLE.EOF Then
      Exit Do
   End If

Loop
MYIMPLEMENTSTABLE.Close
OTHIMPLEMENTSTABLE.Close

'RESEARCH
Forms![OTHER FUNCTIONS]![Status] = "RESEARCH Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYRESEARCHTABLE = TVMINE.OpenRecordset("RESEARCH")
MYRESEARCHTABLE.index = "primarykey"
MYRESEARCHTABLE.MoveFirst

Set OTHRESEARCHTABLE = TVOTH.OpenRecordset("RESEARCH")
OTHRESEARCHTABLE.index = "primarykey"
OTHRESEARCHTABLE.MoveFirst
  
Do Until OTHRESEARCHTABLE.EOF

   MYRESEARCHTABLE.MoveFirst
   MYRESEARCHTABLE.Seek "=", OTHRESEARCHTABLE![Skill], OTHRESEARCHTABLE![TOPIC]
   If MYRESEARCHTABLE.NoMatch Then
      MYRESEARCHTABLE.AddNew
      MYRESEARCHTABLE![Skill] = OTHRESEARCHTABLE![Skill]
      MYRESEARCHTABLE![TOPIC] = OTHRESEARCHTABLE![TOPIC]
      MYRESEARCHTABLE![DL REQUIRED] = OTHRESEARCHTABLE![DL REQUIRED]
      MYRESEARCHTABLE![INFO] = OTHRESEARCHTABLE![INFO]
'      MYRESEARCHTABLE.UPDATE
   End If

   OTHRESEARCHTABLE.MoveNext
   If OTHRESEARCHTABLE.EOF Then
      Exit Do
   End If

Loop
MYRESEARCHTABLE.Close
OTHRESEARCHTABLE.Close

'VALID_BUILDINGS
Forms![OTHER FUNCTIONS]![Status] = "VALID_BUILDINGS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALID_BUILDINGSTABLE = TVMINE.OpenRecordset("VALID_BUILDINGS")
MYVALID_BUILDINGSTABLE.index = "primarykey"
MYVALID_BUILDINGSTABLE.MoveFirst

Set OTHVALID_BUILDINGSTABLE = TVOTH.OpenRecordset("VALID_BUILDINGS")
OTHVALID_BUILDINGSTABLE.index = "primarykey"
OTHVALID_BUILDINGSTABLE.MoveFirst
  
Do Until OTHVALID_BUILDINGSTABLE.EOF

   MYVALID_BUILDINGSTABLE.MoveFirst
   MYVALID_BUILDINGSTABLE.Seek "=", OTHVALID_BUILDINGSTABLE![BUILDINGS]
   If MYVALID_BUILDINGSTABLE.NoMatch Then
      MYVALID_BUILDINGSTABLE.AddNew
      MYVALID_BUILDINGSTABLE![BUILDINGS] = OTHVALID_BUILDINGSTABLE![BUILDINGS]
      MYVALID_BUILDINGSTABLE![SHORTNAME] = OTHVALID_BUILDINGSTABLE![SHORTNAME]
      MYVALID_BUILDINGSTABLE![Update_Field_1] = OTHVALID_BUILDINGSTABLE![Update_Field_1]
      MYVALID_BUILDINGSTABLE![One_Only] = OTHVALID_BUILDINGSTABLE![One_Only]
      MYVALID_BUILDINGSTABLE.UPDATE
   End If

   OTHVALID_BUILDINGSTABLE.MoveNext
   If OTHVALID_BUILDINGSTABLE.EOF Then
      Exit Do
   End If

Loop
MYVALID_BUILDINGSTABLE.Close
OTHVALID_BUILDINGSTABLE.Close

'VALID_CLIMATE
Forms![OTHER FUNCTIONS]![Status] = "VALID_CLIMATE Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALID_CLIMATETABLE = TVMINE.OpenRecordset("VALID_CLIMATE")
MYVALID_CLIMATETABLE.index = "primarykey"
MYVALID_CLIMATETABLE.MoveFirst

Set OTHVALID_CLIMATETABLE = TVOTH.OpenRecordset("VALID_CLIMATE")
OTHVALID_CLIMATETABLE.index = "primarykey"
OTHVALID_CLIMATETABLE.MoveFirst
  
Do Until OTHVALID_CLIMATETABLE.EOF

   MYVALID_CLIMATETABLE.MoveFirst
   MYVALID_CLIMATETABLE.Seek "=", OTHVALID_CLIMATETABLE![CLIMATE], OTHVALID_CLIMATETABLE![ITEM], OTHVALID_CLIMATETABLE![TERRAIN]
   If MYVALID_CLIMATETABLE.NoMatch Then
      MYVALID_CLIMATETABLE.AddNew
      MYVALID_CLIMATETABLE![CLIMATE] = OTHVALID_CLIMATETABLE![CLIMATE]
      MYVALID_CLIMATETABLE![ITEM] = OTHVALID_CLIMATETABLE![ITEM]
      MYVALID_CLIMATETABLE![TERRAIN] = OTHVALID_CLIMATETABLE![TERRAIN]
      MYVALID_CLIMATETABLE![ITEM_NUMBER] = OTHVALID_CLIMATETABLE![ITEM_NUMBER]
      MYVALID_CLIMATETABLE.UPDATE
   End If

   OTHVALID_CLIMATETABLE.MoveNext
   If OTHVALID_CLIMATETABLE.EOF Then
      Exit Do
   End If

Loop
MYVALID_CLIMATETABLE.Close
OTHVALID_CLIMATETABLE.Close

'VALID_CROPS
Forms![OTHER FUNCTIONS]![Status] = "VALID_CROPS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALID_CROPSTABLE = TVMINE.OpenRecordset("VALID_CROPS")
MYVALID_CROPSTABLE.index = "primarykey"
MYVALID_CROPSTABLE.MoveFirst

Set OTHVALID_CROPSTABLE = TVOTH.OpenRecordset("VALID_CROPS")
OTHVALID_CROPSTABLE.index = "primarykey"
OTHVALID_CROPSTABLE.MoveFirst
  
Do Until OTHVALID_CROPSTABLE.EOF

   MYVALID_CROPSTABLE.MoveFirst
   MYVALID_CROPSTABLE.Seek "=", OTHVALID_CROPSTABLE![GOOD]
   If MYVALID_CROPSTABLE.NoMatch Then
      MYVALID_CROPSTABLE.AddNew
      MYVALID_CROPSTABLE![GOOD] = OTHVALID_CROPSTABLE![GOOD]
      MYVALID_CROPSTABLE![GOOD_PRODUCED] = OTHVALID_CROPSTABLE![GOOD_PRODUCED]
      MYVALID_CROPSTABLE![ACRES_PLANTING] = OTHVALID_CROPSTABLE![ACRES_PLANTING]
      MYVALID_CROPSTABLE![ACRES_HARVESTING] = OTHVALID_CROPSTABLE![ACRES_HARVESTING]
      MYVALID_CROPSTABLE![IMPLEMENT] = OTHVALID_CROPSTABLE![IMPLEMENT]
      MYVALID_CROPSTABLE![CROP] = OTHVALID_CROPSTABLE![CROP]
      MYVALID_CROPSTABLE.UPDATE
   End If

   OTHVALID_CROPSTABLE.MoveNext
   If OTHVALID_CROPSTABLE.EOF Then
      Exit Do
   End If

Loop
MYVALID_CROPSTABLE.Close
OTHVALID_CROPSTABLE.Close

'VALID_MINERALS
Forms![OTHER FUNCTIONS]![Status] = "VALID_MINERALS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALID_MINERALSTABLE = TVMINE.OpenRecordset("VALID_MINERALS")
MYVALID_MINERALSTABLE.index = "primarykey"
MYVALID_MINERALSTABLE.MoveFirst

Set OTHVALID_MINERALSTABLE = TVOTH.OpenRecordset("VALID_MINERALS")
OTHVALID_MINERALSTABLE.index = "primarykey"
OTHVALID_MINERALSTABLE.MoveFirst
  
Do Until OTHVALID_MINERALSTABLE.EOF

   MYVALID_MINERALSTABLE.MoveFirst
   MYVALID_MINERALSTABLE.Seek "=", OTHVALID_MINERALSTABLE![MINERAL]
   If MYVALID_MINERALSTABLE.NoMatch Then
      MYVALID_MINERALSTABLE.AddNew
      MYVALID_MINERALSTABLE![MINERAL] = OTHVALID_MINERALSTABLE![MINERAL]
      MYVALID_MINERALSTABLE![MINING_VOLUME_1] = OTHVALID_MINERALSTABLE![MINING_VOLUME_1]
      MYVALID_MINERALSTABLE![MINING_VOLUME_2] = OTHVALID_MINERALSTABLE![MINING_VOLUME_2]
      MYVALID_MINERALSTABLE![MINING_VOLUME_3] = OTHVALID_MINERALSTABLE![MINING_VOLUME_3]
      MYVALID_MINERALSTABLE![MINING_VOLUME_4] = OTHVALID_MINERALSTABLE![MINING_VOLUME_4]
      MYVALID_MINERALSTABLE.UPDATE
   End If

   OTHVALID_MINERALSTABLE.MoveNext
   If OTHVALID_MINERALSTABLE.EOF Then
      Exit Do
   End If

Loop
MYVALID_MINERALSTABLE.Close
OTHVALID_MINERALSTABLE.Close

'VALID_SKILLS
Forms![OTHER FUNCTIONS]![Status] = "VALID_SKILLS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALID_SKILLSTABLE = TVMINE.OpenRecordset("VALID_SKILLS")
MYVALID_SKILLSTABLE.index = "primarykey"
MYVALID_SKILLSTABLE.MoveFirst

Set OTHVALID_SKILLSTABLE = TVOTH.OpenRecordset("VALID_SKILLS")
OTHVALID_SKILLSTABLE.index = "primarykey"
OTHVALID_SKILLSTABLE.MoveFirst
  
Do Until OTHVALID_SKILLSTABLE.EOF

   MYVALID_SKILLSTABLE.MoveFirst
   MYVALID_SKILLSTABLE.Seek "=", OTHVALID_SKILLSTABLE![Skill]
   If MYVALID_SKILLSTABLE.NoMatch Then
      MYVALID_SKILLSTABLE.AddNew
      MYVALID_SKILLSTABLE![Skill] = OTHVALID_SKILLSTABLE![Skill]
      MYVALID_SKILLSTABLE![Group] = OTHVALID_SKILLSTABLE![Group]
      MYVALID_SKILLSTABLE![MORALE] = OTHVALID_SKILLSTABLE![MORALE]
      MYVALID_SKILLSTABLE![SHIP] = OTHVALID_SKILLSTABLE![SHIP]
      MYVALID_SKILLSTABLE![SHORTNAME] = OTHVALID_SKILLSTABLE![SHORTNAME]
      MYVALID_SKILLSTABLE.UPDATE
   End If

   OTHVALID_SKILLSTABLE.MoveNext
   If OTHVALID_SKILLSTABLE.EOF Then
      Exit Do
   End If

Loop
MYVALID_SKILLSTABLE.Close
OTHVALID_SKILLSTABLE.Close

'VALID_SHIPS
Forms![OTHER FUNCTIONS]![Status] = "VALID_SHIPS Table"
Forms![OTHER FUNCTIONS].Repaint
Set MYVALID_SHIPSTABLE = TVMINE.OpenRecordset("VALID_SHIPS")
MYVALID_SHIPSTABLE.index = "primarykey"
MYVALID_SHIPSTABLE.MoveFirst

Set OTHVALID_SHIPSTABLE = TVOTH.OpenRecordset("VALID_SHIPS")
OTHVALID_SHIPSTABLE.index = "primarykey"
OTHVALID_SHIPSTABLE.MoveFirst
  
Do Until OTHVALID_SHIPSTABLE.EOF

   MYVALID_SHIPSTABLE.MoveFirst
   MYVALID_SHIPSTABLE.Seek "=", OTHVALID_SHIPSTABLE![VESSEL]
   If MYVALID_SHIPSTABLE.NoMatch Then
      MYVALID_SHIPSTABLE.AddNew
      MYVALID_SHIPSTABLE![VESSEL] = OTHVALID_SHIPSTABLE![VESSEL]
      MYVALID_SHIPSTABLE![BASE_MP_SAIL] = OTHVALID_SHIPSTABLE![BASE_MP_SAIL]
      MYVALID_SHIPSTABLE![NAV_MOD_SAIL] = OTHVALID_SHIPSTABLE![NAV_MOD_SAIL]
      MYVALID_SHIPSTABLE![SAIL_MOD] = OTHVALID_SHIPSTABLE![SAIL_MOD]
      MYVALID_SHIPSTABLE![SEA_MOD_SAIL] = OTHVALID_SHIPSTABLE![SEA_MOD_SAIL]
      MYVALID_SHIPSTABLE![SAILING_POSSIBLE] = OTHVALID_SHIPSTABLE![SAILING_POSSIBLE]
      MYVALID_SHIPSTABLE![BASE_MP_ROW] = OTHVALID_SHIPSTABLE![BASE_MP_ROW]
      MYVALID_SHIPSTABLE![NAV_MOD_ROW] = OTHVALID_SHIPSTABLE![NAV_MOD_ROW]
      MYVALID_SHIPSTABLE![SEA_MOD_ROW] = OTHVALID_SHIPSTABLE![SEA_MOD_ROW]
      MYVALID_SHIPSTABLE![ROW_MOD] = OTHVALID_SHIPSTABLE![ROW_MOD]
      MYVALID_SHIPSTABLE![ROWING_POSSIBLE] = OTHVALID_SHIPSTABLE![ROWING_POSSIBLE]
      MYVALID_SHIPSTABLE![Crew_Required] = OTHVALID_SHIPSTABLE![Crew_Required]
      MYVALID_SHIPSTABLE![Max_Crew] = OTHVALID_SHIPSTABLE![Max_Crew]
      MYVALID_SHIPSTABLE.UPDATE
   End If

   OTHVALID_SHIPSTABLE.MoveNext
   If OTHVALID_SHIPSTABLE.EOF Then
      Exit Do
   End If

Loop
MYVALID_SHIPSTABLE.Close
OTHVALID_SHIPSTABLE.Close

Forms![OTHER FUNCTIONS]![Status] = ""
Forms![OTHER FUNCTIONS].Repaint

End Function
